---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jaeger-operator
  namespace: flux-system
  labels:
    app.kubernetes.io/part-of: jaeger-operator
spec:
  releaseName: jaeger-operator
  targetNamespace: observability
  dependsOn:
    - name: kube-prometheus-stack
      namespace: monitoring
  interval: 30m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  chart:
    spec:
      chart: jaeger-operator
      sourceRef:
        kind: HelmRepository
        name: jaegertracing
        namespace: flux-system
