---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jaeger
  namespace: flux-system
  labels:
    app.kubernetes.io/part-of: jaeger
spec:
  releaseName: jaeger
  targetNamespace: observability
  interval: 30m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  chart:
    spec:
      chart: jaeger
      sourceRef:
        kind: HelmRepository
        name: jaegertracing
        namespace: flux-system
  values:
    collector:
      service:
        zipkin:
          port: 9411
        otlp:
          grpc:
            name: otlp-grpc
            port: 4317
          http:
            name: otlp-http
            port: 4318
