apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kiali
  namespace: istio-system
spec:
  secretName: kiali-tls
  privateKey:
    rotationPolicy: Always
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  commonName: "kiali.dallin.brewsentry.com"
  dnsNames:
    - "kiali.dallin.brewsentry.com"
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
