---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kiali
  namespace: flux-system
spec:
  releaseName: kiali
  targetNamespace: kiali-operator
  interval: 50m
  chart:
    spec:
      chart: kiali-operator
      sourceRef:
        kind: HelmRepository
        name: kiali
        namespace: flux-system
  values:
    cr:
      create: true
      namespace: istio-system
      spec:
        istio_labels:
          app_label_name: "app.kubernetes.io/name"
          version_label_name: "app.kubernetes.io/version"
        external_services:
          prometheus:
            url: "http://kube-prometheus-stack-prometheus.monitoring:9090"
          grafana:
            auth:
              password: "Grafana&Git0ps"
              type: "none"
              username: "admin"
            enabled: true
            in_cluster_url: 'http://kube-prometheus-stack-grafana.monitoring'
            url: 'https://grafana.dallin.brewsentry.com'
            dashboards:
            - name: "Istio Service Dashboard"
            - name: "Istio Workload Dashboard"
            - name: "Istio Mesh Dashboard"
            - name: "Istio Control Plane Dashboard"
            - name: "Istio Performance Dashboard"
            - name: "Istio Wasm Extension Dashboard"
          istio:
            component_status:
              components:
              - app_label: "istiod"
                is_core: true
                is_proxy: false
              - app_label: "istio-ingressgateway"
                is_core: true
                is_proxy: true
                namespace: "istio-ingress"
              enabled: true
          tracing:
            enabled: true
            in_cluster_url: "http://jaeger-query.observability.svc.cluster.local:16685"
            use_grpc: true
