---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kiali
  namespace: kiali-operator
spec:
  releaseName: kiali
  chart:
    spec:
      chart: kiali-operator
      sourceRef:
        kind: HelmRepository
        name: kiali
  interval: 5m
  values:
    # resources:
    #   requests:
    #     cpu: 100m
    #     memory: 128Mi
    #   limits:
    #     memory: 512Mi
    # replicaCount: 6
    cr:
      create: true
      namespace: istio-system
      spec:
        istio_labels:
          app_label_name: "app.kubernetes.io/name"
          version_label_name: "app.kubernetes.io/version"
        external_services:
          prometheus:
            # Prometheus service name is "metrics" and is in the "telemetry" namespace
            url: "http://kube-prometheus-stack-prometheus.monitoring:9090"
          grafana:
            auth:
              # ca_file: ""
              # insecure_skip_verify: false
              password: "Grafana&Git0ps"
              # token: ""
              type: "none"
              # use_kiali_token: false
              username: "kiali"
            enabled: true
            in_cluster_url: 'http://kube-prometheus-stack-grafana.monitoring'
            url: 'https://grafana.dallin.brewsentry.com'
            dashboards:
            - name: "Istio Service Dashboard"
            - name: "Istio Workload Dashboard"
            - name: "Istio Mesh Dashboard"
            - name: "Istio Control Plane Dashboard"
            - name: "Istio Performance Dashboard"
            - name: "Istio Wasm Extension Dashboard"
          istio:
            component_status:
              components:
              - app_label: "istiod"
                is_core: true
                is_proxy: false
              - app_label: "istio-gateway"
                is_core: true
                is_proxy: true
                namespace: "istio-ingress"
              enabled: true
          tracing:
            enable: false
