---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
  labels:
    app.kubernetes.io/part-of: cert-manager
spec:
  releaseName: cert-manager
  targetNamespace: cert-manager
  interval: 30m
  dependsOn:
    - name: aws-load-balancer-controller
      namespace: flux-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
  values:
    installCRDs: true
    serviceAccount:
      create: true
      annotations:
         eks.amazonaws.com/role-arn: arn:aws:iam::704855531002:role/eks-istio-lab-cert-manager
