apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: podinfo
  namespace: podinfo
spec:
  secretName: podinfo-tls
  privateKey:
    rotationPolicy: Always
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  commonName: "podinfo.BASE_DOMAIN_NAME"
  dnsNames:
    - "podinfo.BASE_DOMAIN_NAME"
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
