apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard
  namespace: istio-ingress
spec:
  secretName: wildcard-tls
  privateKey:
    rotationPolicy: Always
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  commonName: "*.dallin.brewsentry.com"
  dnsNames:
    - "*.dallin.brewsentry.com"
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
