---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cluster-autoscaler
  namespace: cluster-autoscaler
spec:
  releaseName: cluster-autoscaler
  interval: 30m
  chart:
    spec:
      chart: cluster-autoscaler
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: cluster-autoscaler
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    autoDiscovery:
      clusterName: eks-istio-lab
    awsRegion: us-west-2
    cloudProvider: aws
    rbac:
      serviceAccount:
        create: true
        annotations:
          eks.amazonaws.com/role-arn: arn:aws:iam::704855531002:role/
    replicaCount: 2
