---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: cluster-autoscaler
  namespace: flux-system
spec:
  interval: 24h
  url: https://kubernetes.github.io/autoscaler
