---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: flux-system
spec:
  releaseName: podinfo
  targetNamespace: podinfo
  interval: 5m
  chart:
    spec:
      chart: podinfo
      version: ">=6.5.0"
      sourceRef:
        kind: HelmRepository
        name: flux-system
  values:
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        memory: 512Mi
    hpa:
      enabled: true
      maxReplicas: 10
      cpu: 80
    redis:
      enabled: true
      repository: public.ecr.aws/docker/library/redis
      tag: 7
    replicaCount: 2
    serviceMonitor:
      enabled: true
    # ingress:
    #   enabled: true
    #   className: "alb"
    #   annotations:
    #     alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig":
    #       { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    #     alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:us-west-2:704855531002:certificate/aae37b55-e3ed-4c15-88f4-89b94a426a03"
    #     alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    #     alb.ingress.kubernetes.io/scheme: internet-facing
    #     alb.ingress.kubernetes.io/ssl-redirect: "443"
    #     alb.ingress.kubernetes.io/target-type: ip
    #     external-dns.alpha.kubernetes.io/hostname: podinfo.dallin.brewsentry.com
    #   hosts:
    #   - host: podinfo.dallin.brewsentry.com
    #     paths:
    #     - path: /
    #       pathType: Prefix
