---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: flux-system
spec:
  releaseName: podinfo
  targetNamespace: podinfo
  interval: 5m
  chart:
    spec:
      chart: podinfo
      version: ">=6.5.0"
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: flux-system
  values:
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        memory: 512Mi
    hpa:
      enabled: true
      maxReplicas: 10
      cpu: 80
    redis:
      enabled: true
      repository: public.ecr.aws/docker/library/redis
      tag: 7
    replicaCount: 2
    serviceMonitor:
      enabled: true
