apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - podmonitor.yaml
configMapGenerator:
  - name: flux-grafana-dashboards
    files:
      - dashboards/flux/control-plane.json
      - dashboards/flux/cluster.json
      - dashboards/flux/logs.json
    options:
      labels:
        grafana_dashboard: "1"
        app.kubernetes.io/part-of: flux
        app.kubernetes.io/component: monitoring
      annotations:
        k8s-sidecar-target-directory: /tmp/dashboards/Flux
  - name: istio-grafana-dashboards
    files:
      - dashboards/istio/istio-extension-dashboard.json
      - dashboards/istio/istio-mesh-dashboard.json
      - dashboards/istio/istio-performance-dashboard.json
      - dashboards/istio/istio-service-dashboard.json
      - dashboards/istio/istio-workload-dashboard.json
      - dashboards/istio/pilot-dashboard.json
    options:
      labels:
        grafana_dashboard: "1"
        app.kubernetes.io/part-of: istio
        app.kubernetes.io/component: monitoring
      annotations:
        k8s-sidecar-target-directory: /tmp/dashboards/Istio
